name: adaptcmvc
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23.4
  - scikit-learn=1.3.2
  - matplotlib
  - pillow
  - tqdm
  - pip
  - pip:
    - torch==1.12.1
    - torchvision==0.13.1
